# docker-compose.yml 
version: '3'

services:
  portainer:
    image: portainer/portainer-ce:2.20.0
    container_name: portainer
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    volumes:
      - ./portainer-data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 9000:9000