version: '3'
services:
  opensearch-2110-node1: # This is also the hostname of the container within the Docker network (i.e. https://opensearch-node1/)
    image: opensearchproject/opensearch:2.11.0 # Specifying the latest available image - modify if you want a specific version
    container_name: opensearch-2110-node1
    environment:
      - cluster.name=opensearch-2110-cluster # Name the cluster
      - node.name=opensearch-2110-node1 # Name the node that will run in this container
      - discovery.seed_hosts=opensearch-2110-node1,opensearch-2110-node2 # Nodes to look for when discovering the cluster
      - cluster.initial_cluster_manager_nodes=opensearch-2110-node1,opensearch-2110-node2 # Nodes eligible to serve as cluster manager
      - bootstrap.memory_lock=true # Disable JVM heap memory swapping
      - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m" # Set min and max JVM heap sizes to at least 50% of system RAM
    ulimits:
      memlock:
        soft: -1 # Set memlock to unlimited (no soft or hard limit)
        hard: -1
      nofile:
        soft: 65536 # Maximum number of open files for the opensearch user - set to at least 65536
        hard: 65536
    volumes:
      - opensearch-2110-data1:/usr/share/opensearch/data # Creates volume called opensearch-data1 and mounts it to the container
    ports:
      - 9201:9200 # REST API
      - 9601:9600 # Performance Analyzer
    networks:
      - opensearch-net # All of the containers will join the same Docker bridge network
  opensearch-2110-node2:
    image: opensearchproject/opensearch:2.11.0 # This should be the same image used for opensearch-node1 to avoid issues
    container_name: opensearch-2110-node2
    environment:
      - cluster.name=opensearch-2110-cluster
      - node.name=opensearch-2110-node2
      - discovery.seed_hosts=opensearch-2110-node1,opensearch-2110-node2
      - cluster.initial_cluster_manager_nodes=opensearch-2110-node1,opensearch-2110-node2
      - bootstrap.memory_lock=true
      - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - opensearch-2110-data2:/usr/share/opensearch/data
    ports:
      - 9202:9200 # REST API
      - 9602:9600 # Performance Analyzer
    networks:
      - opensearch-net
  opensearch-2110-2-nodes-dashboards:
    image: opensearchproject/opensearch-dashboards:2.11.0 # Make sure the version of opensearch-dashboards matches the version of opensearch installed on other nodes
    container_name: opensearch-2110-dashboards
    ports:
      - 5601:5601 # Map host port 5601 to container port 5601
    expose:
      - "5601" # Expose port 5601 for web access to OpenSearch Dashboards
    environment:
      OPENSEARCH_HOSTS: '["https://opensearch-2110-node1:9200","https://opensearch-2110-node2:9200"]' # Define the OpenSearch nodes that OpenSearch Dashboards will query
    networks:
      - opensearch-net

volumes:
  opensearch-2110-data1:
  opensearch-2110-data2:

networks:
  opensearch-net:
  